global:
  scrape_interval: 15s

rule_files:
  - /etc/prometheus/prometheus-rules.yaml

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: self-healing-demo
    static_configs:
      - targets: ["self-healing-demo.self-healing.svc.cluster.local:80"]

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager.monitoring.svc.cluster.local:9093"]
