apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - controller-rbac.yaml
  - controller-deployment.yaml
  - demo-app.yaml
images:
  - name: ghcr.io/abhishekchauhan9520/devops-project-39-self-healing-infrastructure
    newTag: dev
